
package ui.ssel;

import java.math.BigDecimal;

import javax.swing.JOptionPane;

import vectores.SistemaEcuacionesLineales;

/**
 *
 * @author Jedabero
 */
public class JPanelSSEL extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 7348657567539566467L;
	private int numEc = 3;
    private BigDecimal[][] mainMatriz;
    private int it;
    private BigDecimal tol;
    private SistemaEcuacionesLineales mainSel;
    
    private boolean wasThereAnError = false;
    
    private javax.swing.JTable tblSistRowHeaders;
    private javax.swing.table.DefaultTableModel dtmSistema;
    private String tblSistHeaders[] = new String[numEc+1];
    
    private javax.swing.JTable tblAnalitRowHeaders;
    private javax.swing.table.DefaultTableModel dtmAnal;
    
    private javax.swing.JTable tblIteratRowHeaders;
    private javax.swing.table.DefaultTableModel dtmIter;
    private String tblIterHeaders[];
    
    /**
     * Creates new form JPanelSSEL
     */
    public JPanelSSEL() {
        tblIterHeaders = new String[]{"<html>x<sub>i</sub></html>", "<html>e<sub>i</sub></html>"};
        
        resetTableHeaders();
        
        mainMatriz = new BigDecimal[numEc][numEc+1];
        dtmSistema = new javax.swing.table.DefaultTableModel(mainMatriz, tblSistHeaders);
        
        dtmAnal = new javax.swing.table.DefaultTableModel(mainMatriz, tblSistHeaders);
        
        dtmIter = new javax.swing.table.DefaultTableModel(new BigDecimal[numEc][2], tblIterHeaders);
        
        initComponents();
        tblSistRowHeaders = new resources.RowNumberTable(tblSistema);
        scpSist.setRowHeaderView(tblSistRowHeaders);
        
        
        tblAnalitRowHeaders = new resources.RowNumberTable(tblAnalit);
        scpAnal.setRowHeaderView(tblAnalitRowHeaders);
        
        tblIteratRowHeaders = new resources.RowNumberTable(tblIterat);
        scpItr.setRowHeaderView(tblIteratRowHeaders);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        pnlAnalitico = new javax.swing.JPanel();
        btnGauss = new javax.swing.JButton();
        btnJordan = new javax.swing.JButton();
        btnCramer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        scpAnal = new javax.swing.JScrollPane();
        tblAnalit = new javax.swing.JTable();
        pnlSistema = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spnNumEc = new javax.swing.JSpinner();
        scpSist = new javax.swing.JScrollPane();
        tblSistema = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spnIt = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        txtTol = new javax.swing.JTextField();
        btnJacobi = new javax.swing.JButton();
        btnSeidel = new javax.swing.JButton();
        scpItr = new javax.swing.JScrollPane();
        tblIterat = new javax.swing.JTable();

        pnlAnalitico.setBorder(javax.swing.BorderFactory.createTitledBorder("Métodos Analíticos"));

        btnGauss.setText("Gauss");
        btnGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaussActionPerformed(evt);
            }
        });

        btnJordan.setText("Jordan");
        btnJordan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJordanActionPerformed(evt);
            }
        });

        btnCramer.setText("Cramer");
        btnCramer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCramerActionPerformed(evt);
            }
        });

        jLabel3.setText("Matriz resultante");

        tblAnalit.setModel(dtmAnal);
        scpAnal.setViewportView(tblAnalit);

        javax.swing.GroupLayout pnlAnaliticoLayout = new javax.swing.GroupLayout(pnlAnalitico);
        pnlAnalitico.setLayout(pnlAnaliticoLayout);
        pnlAnaliticoLayout.setHorizontalGroup(
            pnlAnaliticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnaliticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAnaliticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpAnal, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addGroup(pnlAnaliticoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(btnGauss)
                        .addGap(18, 18, 18)
                        .addComponent(btnJordan)
                        .addGap(18, 18, 18)
                        .addComponent(btnCramer)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlAnaliticoLayout.setVerticalGroup(
            pnlAnaliticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnaliticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAnaliticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGauss)
                    .addComponent(btnJordan)
                    .addComponent(btnCramer)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpAnal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSistema.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Sistema de ecuaciones");

        jLabel1.setText("Número de ecuaciones:");

        spnNumEc.setModel(new javax.swing.SpinnerNumberModel(3, 2, 25, 1));
        spnNumEc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnNumEcStateChanged(evt);
            }
        });

        tblSistema.setModel(dtmSistema);
        scpSist.setViewportView(tblSistema);

        javax.swing.GroupLayout pnlSistemaLayout = new javax.swing.GroupLayout(pnlSistema);
        pnlSistema.setLayout(pnlSistemaLayout);
        pnlSistemaLayout.setHorizontalGroup(
            pnlSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpSist)
                    .addGroup(pnlSistemaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(spnNumEc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlSistemaLayout.setVerticalGroup(
            pnlSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSistemaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(spnNumEc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpSist, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Método Iterativos"));

        jLabel4.setText("Iteraciones:");

        spnIt.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(15), Integer.valueOf(5), null, Integer.valueOf(1)));

        jLabel5.setText("Tolerancia:");

        txtTol.setColumns(8);
        txtTol.setText("0.001");

        btnJacobi.setText("Jacobi");
        btnJacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJacobiActionPerformed(evt);
            }
        });

        btnSeidel.setText("Seidel");
        btnSeidel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeidelActionPerformed(evt);
            }
        });

        tblIterat.setModel(dtmIter);
        scpItr.setViewportView(tblIterat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpItr)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnIt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnJacobi)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeidel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnIt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJacobi)
                    .addComponent(btnSeidel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpItr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAnalitico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAnalitico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetTableHeaders(){
        tblSistHeaders = new String[numEc+1];
        for (int i = 0; i < numEc; i++) {
            tblSistHeaders[i] = "<html>x<sub>"+(i+1)+"</sub></html>";
        }
        tblSistHeaders[numEc] = "<html>b</html>";
    }
    
    private void resetTable(int n){
        dtmSistema.setColumnCount(n+1);
        
        boolean disminuyendo = (n<numEc);
        
        if (disminuyendo) {
            dtmSistema.removeRow(n);
            for (int i = 0; i < n; i++) {
                dtmSistema.setValueAt(null, i, n);
            }
        } else {
            dtmSistema.addRow(new Object[n]);   
            for (int i = 0; i < n; i++) {
                dtmSistema.setValueAt(null, i, n-1);
            }
        }
        
    }
    
    private void spnNumEcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnNumEcStateChanged
        int n = Integer.parseInt(((javax.swing.JSpinner) evt.getSource()).getValue().toString());
        resetTable(n);
        numEc = n;
        resetTableHeaders();
        dtmSistema.setColumnIdentifiers(tblSistHeaders);
        
    }//GEN-LAST:event_spnNumEcStateChanged

    private void btnGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaussActionPerformed
        creaMatriz();
        dtmAnal.setDataVector(mainSel.metodoGauss().getMatriz(), tblSistHeaders);
    }//GEN-LAST:event_btnGaussActionPerformed

    private void btnJordanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJordanActionPerformed
        creaMatriz();
        dtmAnal.setDataVector(mainSel.metodoJordan().getMatriz(), tblSistHeaders);
    }//GEN-LAST:event_btnJordanActionPerformed

    private void btnCramerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCramerActionPerformed
        creaMatriz();
        try {
            dtmAnal.setDataVector(mainSel.metodoCramer().getMatriz(),
                    new String[]{"<html>x<sub>i</sub></html>"});
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.getParent(), ex.getMessage(),
                            "Error ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCramerActionPerformed

    private void btnJacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJacobiActionPerformed
        creaMatriz();
        checkIterErrors();
        try {
            dtmIter.setDataVector(mainSel.metodoJacobi(it, tol).getMatriz(),
                    tblIterHeaders);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.getParent(), ex.getMessage(),
                            "Error ", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnJacobiActionPerformed

    private void btnSeidelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeidelActionPerformed
        creaMatriz();
        checkIterErrors();
        try {
            dtmIter.setDataVector(mainSel.metodoSeidel(it, tol).getMatriz(),
                    tblIterHeaders);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.getParent(), ex.getMessage(),
                            "Error ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSeidelActionPerformed

    private void creaMatriz(){
        wasThereAnError = false;
        
        mainMatriz = new BigDecimal[numEc][numEc+1];
        for (int i = 0; i < numEc; i++) {
            for (int j = 0; j < numEc+1; j++) {
                String v = "";
                try {
                    v = dtmSistema.getValueAt(i, j).toString();
                    mainMatriz[i][j] = new BigDecimal(v);
                } catch (Exception e) {
                    wasThereAnError = true;
                    String varerr = ((j<numEc)? "x<sub>"+(j+1)+"</sub>":"b");
                    JOptionPane.showMessageDialog(this,
                            "<html>Ecuación "+(i+1)+", "+varerr+" : "+v+"</html>",
                            "Error en ", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        }
        
        if (!wasThereAnError) {
            mainSel = new SistemaEcuacionesLineales(mainMatriz);
        }
    }
    
    private void checkIterErrors(){
        
        String toltext = txtTol.getText();
        try {
            tol = new BigDecimal(toltext);
        } catch (Exception e) {
            toltext += (toltext.isEmpty())? "Vacío":"";
            JOptionPane.showMessageDialog(this.getParent(),
                    toltext + " es invalido.",
                    "Error en el valor de la Toleracia",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        it = Integer.parseInt(spnIt.getValue().toString());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCramer;
    private javax.swing.JButton btnGauss;
    private javax.swing.JButton btnJacobi;
    private javax.swing.JButton btnJordan;
    private javax.swing.JButton btnSeidel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAnalitico;
    private javax.swing.JPanel pnlSistema;
    private javax.swing.JScrollPane scpAnal;
    private javax.swing.JScrollPane scpItr;
    private javax.swing.JScrollPane scpSist;
    private javax.swing.JSpinner spnIt;
    private javax.swing.JSpinner spnNumEc;
    private javax.swing.JTable tblAnalit;
    private javax.swing.JTable tblIterat;
    private javax.swing.JTable tblSistema;
    private javax.swing.JTextField txtTol;
    // End of variables declaration//GEN-END:variables
}
